apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: dev
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: torpoly/flask-rpol:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: dev
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8888      # External port exposed by the service
      targetPort: 8888  # Internal port in the container
  type: LoadBalancer

