apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: dev
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8888      # External port exposed by the service
      targetPort: 8888  # Internal port in the container
  type: LoadBalancer
